---
# Configuration file for the Bandit python security scanner
# https://bandit.readthedocs.io/en/latest/config.html

# Tests are first included by `tests`, and then excluded by `skips`.
# If `tests` is empty, all tests are are considered included.

tests:
# - B101
# - B102

skips:
<<<<<<< HEAD
  - B101 # skip "assert used" check since assertions are required in pytests
=======
  - B101  # skip "assert used" check since assertions are required in pytests
>>>>>>> 4de6b59dd041229073cb15571ec5a1c005f6cad6
