dist: xenial
language: python
python: 3.7
services: docker
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
install:
  - pip install --upgrade -r requirements-test.txt
before_script:
  - docker-compose up -d
script:
  - pre-commit run --all-files
after_script:
  - docker-compose down
