protocols = imap lmtp

service lmtp {
  inet_listener lmtp {
    address = *
    port = 24
  }
}

# Prosta autoryzacja (dla celów laboratoryjnych)
auth_mechanisms = plain login
passdb {
  driver = passwd-file
  args = /etc/dovecot/users
}
userdb {
  driver = static
  args = uid=vmail gid=vmail home=/var/mail/%u
}