---
name: build

on:
  push:
  pull_request:
  repository_dispatch:
    types: [apb]

env:
  IMAGE_NAME: cisagov/example
  PIP_CACHE_DIR: ~/.cache/pip
  PRE_COMMIT_CACHE_DIR: ~/.cache/pre-commit

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Store installed Python version
        run: |
          echo "::set-env name=PY_VERSION::"\
          "$(python -c "import platform;print(platform.python_version())")"
      - name: Cache pip test requirements
        uses: actions/cache@v1
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: "${{ runner.os }}-pip-test-py${{ env.PY_VERSION }}-\
            ${{ hashFiles('**/requirements-test.txt') }}"
          restore-keys: |
            ${{ runner.os }}-pip-test-py${{ env.PY_VERSION }}-
            ${{ runner.os }}-pip-test-
            ${{ runner.os }}-pip-
      - name: Cache pre-commit hooks
        uses: actions/cache@v1
        with:
          path: ${{ env.PRE_COMMIT_CACHE_DIR }}
          key: "${{ runner.os }}-pre-commit-py${{ env.PY_VERSION }}-\
            ${{ hashFiles('**/.pre-commit-config.yaml') }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements-test.txt
      - name: Set up pre-commit hook environments
        run: pre-commit install-hooks
      - name: Run pre-commit on all files
        run: pre-commit run --all-files
<<<<<<< HEAD
  test:
    runs-on: ubuntu-latest
=======
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine image version
        id: get_ver
        run: |
          echo "##[set-output name=version;]$(./bump_version.sh show)"
      - name: Build docker image
        run: |
          version=$(./bump_version.sh show)
          docker build \
            --tag "$IMAGE_NAME" \
            --build-arg GIT_COMMIT=$(git log -1 --format=%H) \
            --build-arg GIT_REMOTE=$(git remote get-url origin) \
            --build-arg VERSION=${{ steps.get_ver.outputs.version }} \
            .
      - name: Save docker image artifact
        run: |
          mkdir dist
          version=$(./bump_version.sh show)
          docker save $IMAGE_NAME:latest | gzip > dist/image.tar.gz
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
  test:
    runs-on: ubuntu-latest
    needs: [build]
>>>>>>> 4de6b59dd041229073cb15571ec5a1c005f6cad6
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
<<<<<<< HEAD
      - name: Store installed Python version
        run: |
          echo "::set-env name=PY_VERSION::"\
          "$(python -c "import platform;print(platform.python_version())")"
=======
>>>>>>> 4de6b59dd041229073cb15571ec5a1c005f6cad6
      - name: Cache pip test requirements
        uses: actions/cache@v1
        with:
          path: ${{ env.PIP_CACHE_DIR }}
<<<<<<< HEAD
          key: "${{ runner.os }}-pip-test-py${{ env.PY_VERSION }}-\
            ${{ hashFiles('**/requirements-test.txt') }}"
          restore-keys: |
            ${{ runner.os }}-pip-test-py${{ env.PY_VERSION }}-
=======
          key: "${{ runner.os }}-pip-test-\
            ${{ hashFiles('**/requirements-test.txt') }}"
          restore-keys: |
>>>>>>> 4de6b59dd041229073cb15571ec5a1c005f6cad6
            ${{ runner.os }}-pip-test-
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements-test.txt
<<<<<<< HEAD
=======
      - name: Download docker image artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Load docker image
        run: docker load < dist/image.tar.gz
>>>>>>> 4de6b59dd041229073cb15571ec5a1c005f6cad6
      - name: Run tests
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: pytest
